const SEARCH_LIST = "SEARCH_LIST";
const SEARCH_SUCCESS = "SEARCH_SUCCESS";
const SEARCH_FAIL = "SEARCH_FAIL";
const SEARCH_BLOCK = "SEARCH_BLOCK";

// export { SEARCH_LIST, SEARCH_SUCCESS, SEARCH_FAIL, SEARCH_BLOCK };
module.exports = { SEARCH_LIST, SEARCH_SUCCESS, SEARCH_FAIL, SEARCH_BLOCK };
